# Generated by Django 3.2.6 on 2022-04-06 15:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manejadorDeCitas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cita',
            name='estado',
        ),
        migrations.AddField(
            model_name='cita',
            name='asistido',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='cita',
            name='calificacion',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
