# Generated by Django 3.2.6 on 2022-04-06 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('nombre', models.CharField(max_length=50)),
                ('fechaNacimiento', models.DateField()),
                ('correo', models.EmailField(max_length=254)),
                ('tipoDocumento', models.CharField(choices=[('CC', 'CC'), ('TI', 'TI'), ('NIT', 'NIT')], max_length=3)),
                ('numeroDocumento', models.PositiveBigIntegerField(primary_key=True, serialize=False)),
                ('numeroTelefonico', models.PositiveBigIntegerField()),
                ('ciudadania', models.CharField(max_length=50)),
                ('estadoCivil', models.CharField(choices=[('Soltero', 'Soltero'), ('Casado', 'Casado'), ('Divorciado', 'Divorciado')], max_length=20)),
                ('carrera', models.CharField(max_length=50)),
                ('semestre', models.IntegerField()),
            ],
            options={
                'ordering': ['numeroDocumento'],
            },
        ),
    ]
