# Generated by Django 3.2.6 on 2022-04-06 01:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estudiante', '0001_initial'),
        ('universidad', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialAcademico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrera', models.CharField(max_length=50)),
                ('pga', models.FloatField()),
                ('numSemestresCursados', models.IntegerField()),
                ('creditosAprobados', models.IntegerField()),
                ('fechaIngreso', models.DateField()),
                ('creditosActuales', models.IntegerField()),
                ('status', models.BooleanField(default=True)),
                ('estudiante', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='estudiante.estudiante')),
                ('universidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='universidad.universidad')),
            ],
        ),
    ]
