# Generated by Django 3.2.6 on 2022-04-06 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('universidad', '0001_initial'),
        ('estudiante', '0001_initial'),
        ('historialAcademico', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialacademico',
            name='estudiante',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='estudiante.estudiante'),
        ),
        migrations.AlterField(
            model_name='historialacademico',
            name='universidad',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='universidad.universidad'),
        ),
    ]
