# Generated by Django 3.2.12 on 2022-04-07 02:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('universidad', '0001_initial'),
        ('estudiante', '0001_initial'),
        ('historialAcademico', '0002_auto_20220406_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialacademico',
            name='estudiante',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='estudiante.estudiante'),
        ),
        migrations.AlterField(
            model_name='historialacademico',
            name='universidad',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='universidad.universidad'),
        ),
    ]
