# Generated by Django 3.2.6 on 2022-04-06 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estudiante', '0001_initial'),
        ('mentor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id_reporte', models.PositiveBigIntegerField(primary_key=True, serialize=False)),
                ('num_citas_agendadas', models.IntegerField()),
                ('num_citas_canceladas', models.IntegerField()),
                ('num_citas_asistidas', models.IntegerField()),
                ('informe', models.CharField(max_length=340)),
                ('nivel_satisfaccion', models.IntegerField()),
                ('estudiante', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='estudiante.estudiante')),
                ('mentor', models.ManyToManyField(to='mentor.Mentor')),
            ],
        ),
    ]
