# Generated by Django 3.2.6 on 2022-04-06 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporte', '0002_reporte_citas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reporte',
            name='citas',
        ),
    ]
