# Generated by Django 3.2.6 on 2022-04-06 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0001_initial'),
        ('reporte', '0003_remove_reporte_citas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporte',
            name='informe',
            field=models.CharField(default='', max_length=340),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='mentor',
            field=models.ManyToManyField(blank=True, to='mentor.Mentor'),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='nivel_satisfaccion',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='num_citas_agendadas',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='num_citas_asistidas',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='num_citas_canceladas',
            field=models.IntegerField(default=0),
        ),
    ]
